export const articles = [
  {
    author: "John Doe",
    authorProfilePicture: "https://www.example.com/profile/johndoe.jpg",
    articleCoverPicture: "https://picsum.photos/id/101/400/400",
    durationToRead: "10 minutes",
    title: "Introduction to JavaScript",
    description: "Learn the basics of JavaScript programming language.",
    tags: ["JavaScript", "Programming", "Web Development"],
    isPremium: false,
    isSaved: false,
    releaseDate: "2023-05-01",
    body: `JavaScript is a widely-used programming language that is primarily used to add interactivity and dynamic functionality to websites. It allows developers to create dynamic web pages by manipulating elements, handling events, and making HTTP requests. JavaScript is a versatile language with a rich ecosystem of libraries and frameworks, making it a powerful tool for web development. In this article, we will cover the fundamental concepts of JavaScript, including variables, functions, conditionals, loops, and objects. By the end of this article, you will have a solid understanding of JavaScript and be ready to dive deeper into web development using this powerful language. So let's get started on our journey to explore the world of JavaScript!`,
  },
  {
    author: "Jane Smith",
    authorProfilePicture: "https://www.example.com/profile/janesmith.jpg",
    articleCoverPicture: "https://picsum.photos/id/102/400/400",
    durationToRead: "8 minutes",
    title: "Python Tips and Tricks",
    description:
      "Discover useful tips and tricks for efficient Python programming.",
    tags: ["Python", "Programming"],
    isPremium: true,
    isSaved: false,
    releaseDate: "2023-04-25",
    body: `Python is a versatile and powerful programming language known for its simplicity and readability. It is widely used in various domains, including web development, data analysis, scientific computing, artificial intelligence, and more. In this article, we will explore a collection of useful tips and tricks that will help you write efficient and effective Python code. From optimizing loops and using list comprehensions to leveraging built-in functions and libraries, you will discover techniques to improve your Python programming skills. Whether you're a beginner or an experienced developer, these tips and tricks will enhance your productivity and enable you to write cleaner and more maintainable Python code.`,
  },
  {
    author: "Sam Johnson",
    authorProfilePicture: "https://www.example.com/profile/samjohnson.jpg",
    articleCoverPicture: "https://picsum.photos/id/103/400/400",
    durationToRead: "15 minutes",
    title: "Mastering CSS Grid Layout",
    description: "Learn how to create complex web layouts using CSS Grid.",
    tags: ["CSS", "Web Development"],
    isPremium: false,
    isSaved: true,
    releaseDate: "2023-04-20",
    body: "CSS Grid is a powerful layout system that enables you to design complex and responsive web layouts with ease. In this article, you will dive deep into CSS Grid and master its various features and techniques. From creating grid containers to placing and aligning grid items, you will learn how to leverage the power of CSS Grid to build visually stunning and flexible web layouts. Whether you're a beginner or an experienced web developer, this comprehensive guide will enhance your understanding of CSS Grid and take your web design skills to the next level.",
  },
  {
    author: "John Doe",
    authorProfilePicture: "https://www.example.com/profile/johndoe.jpg",
    articleCoverPicture: "https://picsum.photos/id/101/400/400",
    durationToRead: "10 minutes",
    title: "Introduction to JavaScript",
    description: "Learn the basics of JavaScript programming language.",
    tags: ["JavaScript", "Programming", "Web Development"],
    isPremium: false,
    isSaved: false,
    releaseDate: "2023-05-01",
    body: `JavaScript is a widely-used programming language that is primarily used to add interactivity and dynamic functionality to websites. It allows developers to create dynamic web pages by manipulating elements, handling events, and making HTTP requests. JavaScript is a versatile language with a rich ecosystem of libraries and frameworks, making it a powerful tool for web development. In this article, we will cover the fundamental concepts of JavaScript, including variables, functions, conditionals, loops, and objects. By the end of this article, you will have a solid understanding of JavaScript and be ready to dive deeper into web development using this powerful language. So let's get started on our journey to explore the world of JavaScript!`,
  },
  {
    author: "Jane Smith",
    authorProfilePicture: "https://www.example.com/profile/janesmith.jpg",
    articleCoverPicture: "https://picsum.photos/id/102/400/400",
    durationToRead: "8 minutes",
    title: "Python Tips and Tricks",
    description:
      "Discover useful tips and tricks for efficient Python programming.",
    tags: ["Python", "Programming"],
    isPremium: true,
    isSaved: false,
    releaseDate: "2023-04-25",
    body: `Python is a versatile and powerful programming language known for its simplicity and readability. It is widely used in various domains, including web development, data analysis, scientific computing, artificial intelligence, and more. In this article, we will explore a collection of useful tips and tricks that will help you write efficient and effective Python code. From optimizing loops and using list comprehensions to leveraging built-in functions and libraries, you will discover techniques to improve your Python programming skills. Whether you're a beginner or an experienced developer, these tips and tricks will enhance your productivity and enable you to write cleaner and more maintainable Python code.`,
  },
  {
    author: "Sam Johnson",
    authorProfilePicture: "https://www.example.com/profile/samjohnson.jpg",
    articleCoverPicture: "https://picsum.photos/id/103/400/400",
    durationToRead: "15 minutes",
    title: "Mastering CSS Grid Layout",
    description: "Learn how to create complex web layouts using CSS Grid.",
    tags: ["CSS", "Web Development"],
    isPremium: false,
    isSaved: true,
    releaseDate: "2023-04-20",
    body: "CSS Grid is a powerful layout system that enables you to design complex and responsive web layouts with ease. In this article, you will dive deep into CSS Grid and master its various features and techniques. From creating grid containers to placing and aligning grid items, you will learn how to leverage the power of CSS Grid to build visually stunning and flexible web layouts. Whether you're a beginner or an experienced web developer, this comprehensive guide will enhance your understanding of CSS Grid and take your web design skills to the next level.",
  },
];
export const articleCategories = ["Recommendation", "Latest", "Trending"];
export const articleDiscussion = [
  "Code documentation: Who needs it anyway?",
  "Data structures: Just pick one and hope for the best",
  "Debugging: Because bugs are our best friends",
  "JavaScript frameworks: Because we don't have enough already",
  "Clean code: What's the fun in that?",
  "Version control: Who needs to collaborate anyway?",
  "Slow database queries: Embrace the wait",
  "Agile development: Because chaos is the new norm",
];
export const articleLevels = ["Beginner", "Intermediate", "Advance"];
export const articleTopics = [
  "React",
  "Nextjs",
  "Tailwind",
  "React Hook",
  "Agile",
  "SEO",
  "Web Dev",
];
export const articleWriters = [
  {
    id: 12345,
    name: "John Doe",
    job: "Frontend Developer",
    image: "https://picsum.photos/id/101/150/150",
  },
  {
    id: 67890,
    name: "Sarah Johnson",
    job: "Backend Developer",
    image: "https://picsum.photos/id/102/150/150",
  },
  {
    id: 54321,
    name: "Michael Smith",
    job: "UI/UX Designer",
    image: "https://picsum.photos/id/103/150/150",
  },
];
export const articleYourTopics = [
  "React",
  "Nextjs",
  "Tailwind",
  "React Hook",
  "Agile",
  "SEO",
  "Web Dev",
];
